// FIX: Populated constants for UI selectors.
export const BACKGROUND_THEMES = [
  'Studio White',
  'Outdoor Nature',
  'Urban Cityscape',
  'Minimalist Gray',
  'Cozy Interior',
  'Vibrant Abstract',
  'Luxury Marble',
  'Rustic Wood',
  'Industrial Loft',
  'Modern Minimalist',
  'High Contrast Pop Art',
  'Soft Pastel Hues',
  'Sci-Fi Neon Grid',
  'Bohemian & Earthy',
  'Art Deco Glamour',
  'Gourmet Kitchen Counter',
  'Sandy Beach Shore',
  'Lush Jungle Foliage',
  'Dark Academia Library',
  'Cloudscape at Sunset',
];

export const LIGHTING_MOODS = [
  'Bright and Clean',
  'Warm and Golden',
  'Dramatic and Moody',
  'Soft and Diffused',
  'Neon and Edgy',
  'Natural Sunlight',
  'High-Contrast Studio',
  'Golden Hour Glow',
  'Backlit Silhouette',
  'Harsh Direct Sunlight',
  'Mystical Fog & Haze',
  'Studio Ring Light',
  'Candlelit Ambiance',
  'Cyberpunk Neons',
  'Moonlit Silver',
  'Underwater Caustics',
];